pipelines:
  - name: S_Bash_0426
    steps:
      - name: S_Bash_0426
        type: Bash
        configuration:
          runtime:   
            type: image
            image: 
              custom:
                name: gcr.io/ship-rc/ubuntu
                tag: latest 
                registry: BSG_GCPkeys
        execution:
          onExecute:
            - echo "executing step..."
            - |
              [ "$step_image_name" == "gcr.io/ship-rc/ubuntu" ]
            - |
              [ "$step_image_tag" == "latest" ]
